# Created with tools\winget.ps1 from Oracooll/orcl-file-explorer
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Oracooll.OrclFileExplorer
PackageVersion: 1.1.012
InstallerType: exe
Scope: user
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --install --quiet
  SilentWithProgress: --install --quiet
UpgradeBehavior: install
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- DisplayName: Orcl File Explorer
  Publisher: Orcl
  DisplayVersion: 1.1.012
  ProductCode: OrclFileExplorer
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/Oracooll/orcl-file-explorer/releases/download/v1.1.012/orclfx.exe
  InstallerSha256: 6839764C31C31FAAB7C6E1EB6E9C97155461150100556FAE18730EE3AAB5AC84
ManifestType: installer
ManifestVersion: 1.10.0