# Created with tools\winget.ps1 from Oracooll/orcl-file-explorer
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json
PackageIdentifier: Oracooll.OrclFileExplorer
PackageVersion: 1.1.012
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0